### ISSUE TITLE
Is it viable to create separate vendor and app bundles?

### ISSUE THREAD

**Issue by finleysg** [steveblue/angular2-rollup#11]
In your original article, you discuss creating separate bundles, but I see that this is not part of the repo here. With SystemJS and Rollup, is this a viable approach? I would rather not ride the Webpack pony, but that is the only build system I've seen that is creating separate bundles.

**Comment by steveblue** [comment]
That was the recommended approach during beta but since AOT compile became available it's best practice to just bundle the entire app and it's dependencies. AOT only pulls in the parts of Angular your web app imports. The original article is out of date and code mentor doesn't allow editing.

**Comment by finleysg** [comment]
Thanks. I'm a bit uncomfortable with the single bundle approach because, even after tree shaking and uglify, my first real-world app is at 1.8MB (375K after gzip). My mobile users are going to take that full hit every time I push out changes or bug fixes. I read a discussion on the Rollup repo about splitting bundles, and it doesn't look like they have a good path forward at this time.
