### ISSUE TITLE
Unused FormsModule is not removed from the bundle after treeshaking

### ISSUE THREAD

**Issue by dmitrysteblyuk** [steveblue/angular2-rollup#15]
I modified app.module a bit by removing routing and all the modules except BrowserModule. Then I run ngr build --prod and the size of the output bundle is 414kB.

If I include FormsModule back in AppModule imports, the bundle is bigger by ~100kB which is about the size of the whole FormsModule minified. Despite FormsModule is never used in the app. So why it's not getting treeshaked?

**Comment by steveblue** [comment]
Thats a good question. If you import a module, it will still be imported by `ngc`. If you are not using a Module, don't import it. You can see this in `ngfactory/tmp/app/shared/app.module.ngfactory.ts`. You can find references to it still in `bundle.js`. 

The bundle can be gzipped and you should see a drastic size reduction. 

```
ngr --build prod
tar -zcvf build/bundle.tar.gz build/bundle.js
```

When I omit FormsModule heres what I get on the master branch right now.

bundle.js - 353 KB
bundle.tar.gz - 90 KB

With FormsModule

bundle.js - 418KB
bundle.tar.gz - 102 KB

In the near future, I plan on writing a build that should be even smaller on load with [Splittable](https://github.com/cramforce/splittable/pull/47) but there are limitations there while it can support lazy loading. If anyone wants to contribute this build that would be awesome!

You could also build `ngc` => `ClosureCompiler`, omitting Rollup. Right now this is not possible from what I understand, but the core team and Contributors are [working on it](https://github.com/alexeagle/closure-compiler-angular-bundling). It is most likely essential for the core team to figure out how to do it for teams at Google. 

Optimizations with the production build will most likely be better over time, Angular 4 already was a great move in that direction. 

@mlaval [ demos all the ways Angular prod build can be optimized ](https://github.com/mlaval/optimize-angular-app).

**Comment by dmitrysteblyuk** [comment]
So what's the point of treeshaking then if not to remove from the bundle unused components and directives of imported modules? If I import a module but don't include it in NgModule imports then I can use tslint (unused-variables) to find imports I don't use and treeshaking would be absolutely useless.

**Comment by steveblue** [comment]
I was curious to benchmark the prod build post Angular 4 and it is quite impressive. 

[screen shot 2017-04-26 at 9 58 18 pm](https://cloud.githubusercontent.com/assets/1171943/25468556/93fb3098-2acb-11e7-9983-9e43d753b470.png)

**Comment by steveblue** [comment]
@dmitrysteblyuk It boils down to how the Modules are exported and how well the tool can interpret the code. The core team made a new setting in the `compilerOptions` for `ngc` called `annotateForClosureCompiler`. This should allow ClosureCompiler to interpret `ngfactory` and treeshake the codebase further.

Consider this:

If you `import` FormsModule but don't inject it via `imports`, it will not be compiled by `ngc`.

```
import { NgModule }      from '@angular/core';
import { HttpModule }    from '@angular/http';
import { CommonModule }  from '@angular/common';
import { FormsModule }   from '@angular/forms';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { AppComponent }  from './app.component';
import { routing }       from './app.routes';
import { HomeModule } from './shared/components/home/home.module';

@NgModule({

    imports: [ BrowserModule,
               BrowserAnimationsModule,
               HttpModule,
               CommonModule,
               HomeModule,
               routing],
    declarations: [ AppComponent ],
    bootstrap:    [ AppComponent ]
})

export class AppModule {}

```

**Comment by dmitrysteblyuk** [comment]
My bundle looks less optimistic but after gzipping it's about 157kB.
![1](https://cloud.githubusercontent.com/assets/19614814/25469205/92d55f56-2b23-11e7-96f7-c3b3c30c17b8.png)

It was just my understanding that rollup can indeed treeshake unused code, and I found it weird that it doesn't apply to angular 2 modules. And then the question is why to use rollup at all if treeshaking has no effect. The case when I do not inject imported modules can be easily (and preferably) handled by lint.

**Comment by steveblue** [comment]
Rollup isn't the only tool that is treeshaking. `ngc`, `Rollup`, and `ClosureCompiler` are all tree shaking and optimizing the bundle.

**Comment by dmitrysteblyuk** [comment]
Ok, thanks. I'll try ClosureCompiler. By the way, do you know by any chance if it can handle lazy loaded modules properly?

**Comment by steveblue** [comment]
Well 157KB isn't bad. When an application scales its probably more beneficial to `lazyload` or `prerender`.

**Comment by steveblue** [comment]
@mlaval proved it can be done https://mlaval.github.io/optimize-angular-app/

**Comment by dmitrysteblyuk** [comment]
Thanks for the link! ClosureCompilre produces the smallest bundle indeed. Prerender is also super fast.
