### ISSUE TITLE
How to include third party libraries?

### ISSUE THREAD

**Issue by Ks89** [steveblue/angular2-rollup#17]
Hi! How can I include other libraries to this project?

I want to use this project as an official rollup example of a library that I published on npm, but I don't know how to include my library and other deps (like hammerjs, mousetrap and font-awesome) to this project, because I'm not a rollup expert.

Thank u.

**Comment by steveblue** [comment]
@Ks89 

How that library is integrated with the build depends on a few factors:

- Does the library conform to Angular Package Spec 4.0?
    YES: Will be bundled via AOT compile
     NO: See next question
- Is the library written in ES2015?
     YES: Can most likely be bundled by default with Rollup
     NO: See next question
- Is the library formatted with UMD modules?
            YES: Edit `rollup.config.js` so Rollup can bundle the library
                    In `rollup.config.js` :
                    `RxJS` is already being included this way
 ```
    commonjs({
     include: 'node_modules/rxjs/**'
    }),
```
            NO: You must include the library globally via `<head>` or `SystemJS`. Examples of both are in    `/src/public/index.html`


You can configure libraries to get copied into a folder in the build in `build.config.js`. You can see that some libraries are already configured here to get copied.

```
module.exports = {
    dep: {
        lib: [
            'core-js',
            'reflect-metadata',
            'zone.js',
            'systemjs',
            '@angular',
            'rxjs'
        ],
        src: './node_modules',
        dist: './build/lib'
    },```

**Comment by steveblue** [comment]
This information should probably be in the README.md

**Comment by steveblue** [comment]
Oh wait, this info is in the README. Closing.

**Comment by Ks89** [comment]
thank u, i will try it
