### ISSUE TITLE
include config.prod.js + config.local.js

### ISSUE THREAD

**Issue by GoNode5** [steveblue/angular2-rollup#3]
please include both files. node is asking for config.prod.js (you would expect config.local.js)

**Comment by steveblue** [comment]
Ok, I will consider this for next release and will add. I usually do not include b/c I don't have server info tracked in github. There are instructions in the README after the Quick Start that show how to add the files.

**Comment by steveblue** [comment]
@GoNode5  Fixed in commit e9022bb75562a48b5b4a8bc14bb0350127384b18
