### ISSUE TITLE
include real project

### ISSUE THREAD

**Issue by GoNode5** [steveblue/angular2-rollup#4]
When starting the first time you only see a black logo. This is confusing, it looks like its not working. Maybe its beter to just include the Heroes example from Angular.io

**Comment by steveblue** [comment]
@GoNode5 If you fork and submit a pull request with TOH added, we will incorporate.

**Comment by GoNode5** [comment]
I'am trying to start a project but your structure doesnt seems to be common angular.io

**Comment by steveblue** [comment]
@GoNode5 The only difference is main.ts is in / and not /src and thats b/c relative paths and npc / ts compilation is not easy to rangle

**Comment by steveblue** [comment]
Since this has not been resolved and including a more sophisticated project will result in more work using this as boilerplate, I have opted to close this issue.
