### ISSUE TITLE
Prod build failed

### ISSUE THREAD

**Issue by olegreznichenko** [steveblue/angular2-rollup#6]
When start ```NODE_ENV=prod npm start``` rollup failed bundling ```LOG Rollup started bundling ngfactory```
```The `this` keyword is equivalent to `undefined` at the top level of an ES module, and has been rewritten```(8x)
And then get error
```
Could not load C:\Users\Олег\Desktop\test/node_modules/rxjs-es/Subject
(imported by C:\Users\Олег\Desktop\test\node_modules\@angular\core\src\facade\async.js)
: ENOENT: no such file or directory, open 'C:\Users\Олег\Desktop\test\node_modules\rxjs-es\Subject'
Error: Could not load C:\Users\Олег\Desktop\test/node_modules/rxjs-es/Subject (imported by C:\Users\Олег\Desktop\test\node_modules\@angular\core\src\facade\async.js)
: ENOENT: no such file or directory, open 'C:\Users\Олег\Desktop\test\node_modules\rxjs-es\Subject'
    at C:\Users\Олег\Desktop\test\node_modules\rollup\src\Bundle.js:184:11
```
Subject exist in node_modules/rxjs-es

**Comment by olegreznichenko** [comment]
![1](https://cloud.githubusercontent.com/assets/11960153/18582568/6e59241a-7c0e-11e6-8d1e-a41abf9a5db1.png)

**Comment by Mig1st4ck** [comment]
Same problem Here.

**Comment by steveblue** [comment]
@Mig1st4ck @olegreznichenko  `The `this` keyword is equivalent to `undefined` at the top level of an ES module, and has been rewritten` is a warning and should be ignored, Rollup is just doing what it does.

The second issue could be Windows specific possibly and may require you to use a custom plugin for rxjs in rollup.config.js. Notice the `\` in the file path? 

Take a look at this StackOverflow and see if it helps you:
http://stackoverflow.com/questions/39490738/outersubscriber-is-not-defined-when-bundeling-with-rollup-js/39504769?noredirect=1#comment66339077_39504769

**Comment by steveblue** [comment]
@Mig1st4ck @olegreznichenko have either of you tried the above suggestion?

**Comment by olegreznichenko** [comment]
@steveblue  I will try to do that today
Also, I check build on ubuntu and all is fine, if I fix it on windows then can do work with pull request

**Comment by Mig1st4ck** [comment]
yes, it worked, but i used the commented part.

````

  plugins: [
    {
      resolveId: function resolveId(id, from){
        if (id.startsWith('rxjs/') || id.startsWith('rxjs\\')){
          //let result = `${__dirname}/temp/rxjs/${id.replace('rxjs/', '')}.js`;
          let result = `${__dirname}/node_modules/rxjs-es/${id.replace('rxjs/', '')}.js`;
          return result.replace(/\//g, "\\");
        }
      }
    },
```

**Comment by steveblue** [comment]
TY for testing @Mig1st4ck Please submit a PR with the change.

**Comment by goleary** [comment]
I've tried everything mentioned in this thread and can't get it to work correctly.

I was attempting to use this starter project to provider a repro for a lib owner to show that theirs isn't working with rollup, but I can't even get this project to work out of the box.  I've gone with this starter instead: https://github.com/mgechev/angular2-rollup-build

**Comment by Raisolution** [comment]
Indeed as @goleary said, the issue is still present. The "windows fix for Rollup" from Sep 24 seems to not work on my end. Here is the output:

![rollup](https://cloud.githubusercontent.com/assets/730205/21933684/0478bc64-d9af-11e6-9453-1c905068586b.png)
